/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventariog;

import com.itextpdf.text.DocumentException;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author José Domingo
 */
public class ConteoArticulos extends javax.swing.JFrame {

    /**
     * Creates new form ConteoArticulos
     */
    private JFileChooser fileChooser = new JFileChooser();
    private String ruta = "";
    private ArrayList<Articulo> listaBaseLeida = new ArrayList<>();
    Operaciones op = new Operaciones();
    Revision r = new Revision();

    public ConteoArticulos() {
        initComponents();
    }

    public void llenarTable() {
        String[][] datosTabla = new String[op.getNuevaLista().size()][5];
        for (int i = 0; i < op.getAgregaContado().size(); i++) {
            datosTabla[i][0] = String.valueOf(op.getNuevaLista().get(i).getNumero());
            datosTabla[i][1] = op.getNuevaLista().get(i).getEan();
            datosTabla[i][2] = op.getNuevaLista().get(i).getCodigo();
            datosTabla[i][3] = op.getNuevaLista().get(i).getDescripcion();
            datosTabla[i][4] = op.getNuevaLista().get(i).getZona();
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                datosTabla,
                new String[]{
                    "Numero", "Codigo de barras", "Codigo", "Descripcion", "Zona"
                }
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        labelCodigo = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        btnContar = new javax.swing.JButton();
        labelArtContado = new javax.swing.JLabel();
        labelArtCuenta = new javax.swing.JLabel();
        labelContadosNum = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        labelTotalNum = new javax.swing.JLabel();
        labelEstado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        labelZona = new javax.swing.JLabel();
        tfZona = new javax.swing.JTextField();
        btnZona = new javax.swing.JButton();
        lblzona = new javax.swing.JLabel();
        lblConteoZona = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuCargar = new javax.swing.JMenuItem();
        menuReporte = new javax.swing.JMenuItem();
        menuReporteDiferencias = new javax.swing.JMenuItem();
        menuReportePdf = new javax.swing.JMenuItem();
        menuRevisionInventario = new javax.swing.JMenu();
        menuRevinv = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();
        menuAyuda = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventario");

        labelCodigo.setText("Codigo del articulo:");
        labelCodigo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        tfCodigo.setEnabled(false);

        btnContar.setText("Contar");
        btnContar.setEnabled(false);
        btnContar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContarActionPerformed(evt);
            }
        });
        btnContar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnContarKeyPressed(evt);
            }
        });

        labelArtCuenta.setText("Articulos Contados:");

        labelContadosNum.setText("No se ha iniciado conteo");

        labelTotal.setText("Total de articulos contados:");

        labelTotalNum.setText("No se ha iniciado conteo");

        labelEstado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelEstado.setForeground(new java.awt.Color(255, 0, 0));
        labelEstado.setText("Base cargada");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Numero", "Clave articulo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        labelZona.setText("Zona:");

        tfZona.setEnabled(false);

        btnZona.setText("Establecer zona");
        btnZona.setEnabled(false);
        btnZona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaActionPerformed(evt);
            }
        });

        lblzona.setText("Articulos contados por zona:");

        lblConteoZona.setText("No se ha inciado conteo");

        menuArchivo.setText("Archivo");

        menuCargar.setText("Cargar base");
        menuCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCargarActionPerformed(evt);
            }
        });
        menuArchivo.add(menuCargar);

        menuReporte.setText("Exportar reporte conteo");
        menuReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReporteActionPerformed(evt);
            }
        });
        menuArchivo.add(menuReporte);

        menuReporteDiferencias.setText("Exportar reporte diferencias");
        menuReporteDiferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReporteDiferenciasActionPerformed(evt);
            }
        });
        menuArchivo.add(menuReporteDiferencias);

        menuReportePdf.setText("Exportar reporte PDF");
        menuReportePdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportePdfActionPerformed(evt);
            }
        });
        menuArchivo.add(menuReportePdf);

        jMenuBar1.add(menuArchivo);

        menuRevisionInventario.setText("Revisión");

        menuRevinv.setText("Revisión de Inventario");
        menuRevinv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRevinvActionPerformed(evt);
            }
        });
        menuRevisionInventario.add(menuRevinv);

        jMenuBar1.add(menuRevisionInventario);

        menuAbout.setText("Ayuda");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });

        menuAyuda.setText("Acerca de");
        menuAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAyudaActionPerformed(evt);
            }
        });
        menuAbout.add(menuAyuda);

        jMenuBar1.add(menuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnContar, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfZona, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnZona))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelArtContado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelArtCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelContadosNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(labelZona, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTotal)
                                    .addComponent(lblzona))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblConteoZona)
                                    .addComponent(labelTotalNum, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(labelEstado)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCodigo)
                            .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(labelArtContado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelContadosNum, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelArtCuenta))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTotal)
                            .addComponent(labelTotalNum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblzona)
                            .addComponent(lblConteoZona))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnContar)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelZona)
                            .addComponent(tfZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnZona))
                        .addGap(117, 117, 117))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menuAboutActionPerformed

    private void menuAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAyudaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Desarrollado por: Jose Domingo Juarez Camacho \n ::: Version: 1.0:::\n"
                + "d-_-b");
    }//GEN-LAST:event_menuAyudaActionPerformed

    private void menuCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCargarActionPerformed
        // TODO add your handling code here:
        fileChooser.showOpenDialog(fileChooser);
        ruta = fileChooser.getSelectedFile().getAbsolutePath();
        op.leerArchivoBase(ruta);
        tfCodigo.setEnabled(true);
        btnContar.setEnabled(true);
        tfZona.setEnabled(true);
        btnZona.setEnabled(true);
        labelEstado.setForeground(new Color(0, 240, 10));
    }//GEN-LAST:event_menuCargarActionPerformed

    private void btnContarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContarActionPerformed
        if(!tfCodigo.getText().equals("")){
        op.conteoDeArticulos(tfCodigo.getText());
        labelArtContado.setText(tfCodigo.getText());
        tfCodigo.setText("");
        labelContadosNum.setText(String.valueOf(op.getTotalPorArticulo()));
        labelTotalNum.setText(String.valueOf(op.getAgregaContado().size()));
        lblConteoZona.setText(String.valueOf(op.getContadorZona()));
        llenarTable();
        }else{
            JOptionPane.showMessageDialog(null, "No has introducido ningún código", "Codigo vacío", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnContarActionPerformed

    private void btnContarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnContarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContarKeyPressed

    private void menuReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReporteActionPerformed
        try {
            op.generaReporteConteo();
        } catch (IOException ex) {
            Logger.getLogger(ConteoArticulos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuReporteActionPerformed

    private void menuReporteDiferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReporteDiferenciasActionPerformed
        try {
            op.gererarReporteDiferencias();
        } catch (IOException ex) {
            Logger.getLogger(ConteoArticulos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuReporteDiferenciasActionPerformed

    private void menuReportePdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportePdfActionPerformed
        try {
            // TODO add your handling code here:
            op.generarReportePdf();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ConteoArticulos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(ConteoArticulos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuReportePdfActionPerformed

    private void btnZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaActionPerformed
        // TODO add your handling code here:
        op.establecerZona(tfZona.getText());
        JOptionPane.showMessageDialog(null, "La zona establecida es " + tfZona.getText(), "ZONA", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnZonaActionPerformed

    private void menuRevinvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRevinvActionPerformed
        // TODO add your handling code here:
       r.setVisible(true);
       r.obtenerListas(op.getIndicesRevision(), op.getListaContados(), op.getListaBase());
    }//GEN-LAST:event_menuRevinvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConteoArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConteoArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConteoArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConteoArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConteoArticulos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContar;
    private javax.swing.JButton btnZona;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelArtContado;
    private javax.swing.JLabel labelArtCuenta;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelContadosNum;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelTotalNum;
    private javax.swing.JLabel labelZona;
    private javax.swing.JLabel lblConteoZona;
    private javax.swing.JLabel lblzona;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem menuAyuda;
    private javax.swing.JMenuItem menuCargar;
    private javax.swing.JMenuItem menuReporte;
    private javax.swing.JMenuItem menuReporteDiferencias;
    private javax.swing.JMenuItem menuReportePdf;
    private javax.swing.JMenuItem menuRevinv;
    private javax.swing.JMenu menuRevisionInventario;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfZona;
    // End of variables declaration//GEN-END:variables
}
