/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventariog;

import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.CreationHelper;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Workbook;

/**
 *
 * @author José Domingo
 */
public class Revision extends javax.swing.JFrame {
    
    private ArrayList<Integer> indices = new ArrayList<>();
    private ArrayList<Articulo> contadosRevision = new ArrayList<>();
    private ArrayList<Articulo> listaBase = new ArrayList<>();
    private ArrayList<Articulo> sinDiferencia = new ArrayList<>();
    int i = 0;
    int editarPosicion = 0;

    /**
     * Creates new form Revision
     */
    public Revision() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblArticulo = new javax.swing.JLabel();
        javax.swing.JLabel lblDescripcion = new javax.swing.JLabel();
        lblMostrarArt = new javax.swing.JLabel();
        lblMostrarDesc = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tfCantidad = new javax.swing.JTextField();
        lblCantidad = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnReporteR = new javax.swing.JButton();
        lblSistema = new javax.swing.JLabel();
        tfSistema = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblArticulo.setText("Articulo");

        lblDescripcion.setText("Descripcion");

        lblMostrarArt.setText("---");

        lblMostrarDesc.setText("----");

        jButton1.setText("Cerrar Ventana");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Siguiente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tfCantidad.setEnabled(false);

        lblCantidad.setText("Cantidad");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnReporteR.setText("Reporte revisado");
        btnReporteR.setActionCommand("Reporte revidado");
        btnReporteR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteRActionPerformed(evt);
            }
        });

        lblSistema.setText("Sistema");

        tfSistema.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblArticulo)
                    .addComponent(lblMostrarArt))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescripcion)
                    .addComponent(lblMostrarDesc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSistema)
                    .addComponent(tfSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantidad))
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(63, 63, 63)
                .addComponent(btnGuardar)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReporteR)
                    .addComponent(btnEditar))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArticulo)
                    .addComponent(lblDescripcion)
                    .addComponent(lblCantidad)
                    .addComponent(lblSistema))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMostrarArt)
                    .addComponent(lblMostrarDesc)
                    .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnGuardar)
                    .addComponent(btnEditar))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnReporteR)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void obtenerListas(ArrayList<Integer> indices, ArrayList<Articulo> contadosRevision, ArrayList<Articulo> base){
        this.indices = indices;
        System.out.println("ind"+indices.size());
        this.contadosRevision = contadosRevision;
        this.listaBase = base;
        System.out.println("cont" + contadosRevision.size());
    }
    
    public void reporteRevision() throws  IOException{
        String marca = "";
        Workbook wb = new HSSFWorkbook();
        CreationHelper createHelper = wb.getCreationHelper();
        org.apache.poi.ss.usermodel.Sheet hoja1 = wb.createSheet("Reporte revisado");

        Row fila1 = hoja1.createRow(0);
        fila1.createCell(0).setCellValue("Codigo de Producto");
        fila1.createCell(1).setCellValue("Nombre de Producto");
        fila1.createCell(2).setCellValue("Cantidad");
        fila1.createCell(3).setCellValue("Lote");
        fila1.createCell(4).setCellValue("ean13");
  
        int rowNum = 1;
        int numero = 1;
        int n1 = 0, n2 = 0;
        for (int i = 0; i < contadosRevision.size(); i++) {

            Row row = hoja1.createRow(rowNum++);
            row.createCell(0).setCellValue(contadosRevision.get(i).getCodigo());
            row.createCell(1).setCellValue(contadosRevision.get(i).getDescripcion());
            row.createCell(2).setCellValue(contadosRevision.get(i).getCantidad());
            row.createCell(3).setCellValue(contadosRevision.get(i).getLote());
            row.createCell(4).setCellValue(contadosRevision.get(i).getEan());
           
        }
        marca = JOptionPane.showInputDialog("Marca:");
        String archivo = "Reporte revision " + marca;
        System.out.println("Reporte creado");
        FileOutputStream fileOut = new FileOutputStream(archivo + ".xls");
        wb.write(fileOut);
        fileOut.close();
    }
    
    public void reporteRevisionSoloDiferencias() throws  IOException{
        String marca = "";
        Workbook wb = new HSSFWorkbook();
        CreationHelper createHelper = wb.getCreationHelper();
        org.apache.poi.ss.usermodel.Sheet hoja1 = wb.createSheet("Reporte revisado");

        Row fila1 = hoja1.createRow(0);
        fila1.createCell(0).setCellValue("Codigo de Producto");
        fila1.createCell(1).setCellValue("Nombre de Producto");
        fila1.createCell(2).setCellValue("Cantidad");
        fila1.createCell(3).setCellValue("Lote");
        fila1.createCell(4).setCellValue("ean13");
  
        int rowNum = 1;
        int numero = 1;
        int n1 = 0, n2 = 0;
        for (int i = 0; i < sinDiferencia.size(); i++) {

            Row row = hoja1.createRow(rowNum++);
            row.createCell(0).setCellValue(sinDiferencia.get(i).getCodigo());
            row.createCell(1).setCellValue(sinDiferencia.get(i).getDescripcion());
            row.createCell(2).setCellValue(sinDiferencia.get(i).getCantidad());
            row.createCell(3).setCellValue(sinDiferencia.get(i).getLote());
            row.createCell(4).setCellValue(sinDiferencia.get(i).getEan());
           
        }
        marca = JOptionPane.showInputDialog("Marca:");
        String archivo = "Reporte importacion " + marca;
        System.out.println("Reporte creado");
        FileOutputStream fileOut = new FileOutputStream(archivo + ".xls");
        wb.write(fileOut);
        fileOut.close();
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(i < indices.size()){
            editarPosicion = indices.get(i);
            lblMostrarArt.setText(contadosRevision.get(indices.get(i)).getCodigo());
            lblMostrarDesc.setText(contadosRevision.get(indices.get(i)).getDescripcion());
            tfSistema.setText(String.valueOf(listaBase.get(indices.get(i)).getCantidad()));
            tfCantidad.setText(String.valueOf(contadosRevision.get(indices.get(i)).getCantidad()));
            System.out.println("vv" + contadosRevision.get(indices.get(i)).getCantidad());
            i++; 
        }else{
            JOptionPane.showMessageDialog(null, "Revisión terminada");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        System.out.println("antes"+ contadosRevision.get(editarPosicion).getCantidad());
        contadosRevision.get(editarPosicion).setCantidad(Integer.parseInt(tfCantidad.getText()));
        System.out.println("despues"+ contadosRevision.get(editarPosicion).getCantidad());
        tfCantidad.setEnabled(false);
        sinDiferencia.add(new Articulo(contadosRevision.get(editarPosicion).getCodigo(),
                                        contadosRevision.get(editarPosicion).getDescripcion(),
                                        contadosRevision.get(editarPosicion).getCantidad(),
                                        contadosRevision.get(editarPosicion).getLote(),
                                        contadosRevision.get(editarPosicion).getEan()));
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        tfCantidad.setEnabled(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnReporteRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteRActionPerformed
        try {
            // TODO add your handling code here:
            reporteRevision();
            reporteRevisionSoloDiferencias();
        } catch (IOException ex) {
            Logger.getLogger(Revision.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReporteRActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnReporteR;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblArticulo;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblMostrarArt;
    private javax.swing.JLabel lblMostrarDesc;
    private javax.swing.JLabel lblSistema;
    private javax.swing.JTextField tfCantidad;
    private javax.swing.JTextField tfSistema;
    // End of variables declaration//GEN-END:variables
}
